apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calendar-backend-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: calendar
    app.kubernetes.io/name: calendar-backend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Evofront-Pvt-Ltd/Calendar-backend.git
    targetRevision: develop
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: calendar-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: calendar-backend
      jsonPointers:
        - /spec/replicas
