apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: calendar-backend
    newName: mohankatari/calendar-backend
    newTag: 3994b957a20c752ebb280bfd3300f72d0a9c9d0f
