apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: calendar-backend
    newName: mohankatari/calendar-backend
    newTag: 6d935bf9380a1fb1089eaafe4f7a08bfeb83a4b5
