apiVersion: v1
kind: Namespace
metadata:
  name: calendar-mongodb
  labels:
    app.kubernetes.io/part-of: calendar
    app.kubernetes.io/name: calendar-mongodb
    app.kubernetes.io/component: database
