apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: calendar-mongodb
  labels:
    app: mongodb
    app.kubernetes.io/part-of: calendar
    app.kubernetes.io/name: calendar-mongodb
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: mongodb
